name: "Euthyrox"

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  Push:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Cyber Park Push'
        run: |
          sed -i 's/CORID=""/CORID="${{ secrets.corid }}"/' ./Euthyrox.sh
          sed -i 's/AGENTID=0/AGENTID=${{ secrets.agentid }}/' ./Euthyrox.sh
          sed -i 's/APPSECRET=""/APPSECRET="${{ secrets.appsecret }}"/' ./Euthyrox.sh
          bash ./Euthyrox.sh
